### ISSUE TITLE
How do we handle fleeing a fight? How do we handle restepping on shops?

### ISSUE THREAD

**Issue by rtsai0104** [Pawtang/roguelike#17]
Also when we walk into a room do we reveal all the walls surrounding your space

**Comment by Pawtang** [comment]
I think all walls should be visible when the dungeon  level is generated

What else about fleeing?

**Comment by rtsai0104** [comment]
If we flee from a fight, do we keep the monster fight on that space? Or do we kick the person back to the previous space? Or do we just do what we do now, mark the room as completed, and restepping on that space does nothing. Just some thoughts

**Comment by Pawtang** [comment]
I think if we lower the monster spawn rate, the monster should still be in that square and become marked on the map, but otherwise with the current spawn rate you should be able to flee and the monster is just gone.
