### ISSUE TITLE
Any reason not to use Github pages?

### ISSUE THREAD

**Issue by SouDescolado** [Pawtang/roguelike#39]
I did a fork and, with some tinkering, I managed to host with github pages
https://soudescolado.github.io/roguelike/

Is there any specific reason not to use it?

**Comment by Pawtang** [comment]
Not really - I have just been using Netlify for a little while and haven't tried github pages yet. Is there any advantage to hosting w/ github?

**Comment by SouDescolado** [comment]
The main advantage is that you push updates and it is live. You dont have the hassle to get all the files and upload somewhere else

**Comment by Pawtang** [comment]
You get the same thing with Netlify, it connects to your repositories:
https://www.netlify.com/github-pages-vs-netlify/

Pretty cool option

**Comment by SouDescolado** [comment]
Oh, so it is an integration thing.
Usually, unless there is a need for SQL or something, I see games being hosted on github pages instead of another service, but it looks like it have no differences (while netlify promises more than github). Thanks!
